# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSeccure < Formula
  desc "Pure-Go port of SECCURE — byte-compatible with the C reference and py-seccure across all 15 curves."
  homepage "https://github.com/invenity-labs/go-seccure"
  version "0.2.1"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.1/go-seccure_0.2.1_darwin_amd64.tar.gz"
      sha256 "33e51cf3b9a430e6ca822f9d2932d06091052469fd9914331c7f728687016ae5"

      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.1/go-seccure_0.2.1_darwin_arm64.tar.gz"
      sha256 "73980ae43d9f6762e9d3e7170d4bdf70109dd2c048bb1561760e91f1c9cbf9ae"

      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.1/go-seccure_0.2.1_linux_amd64.tar.gz"
      sha256 "cdaa9817247a6c2eb3fb3155f0ad4398f93f7c2c345354d891b24735ee4eab31"
      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.1/go-seccure_0.2.1_linux_arm64.tar.gz"
      sha256 "bf3ceec2a3732967392fb7eb3b6b0bf9837c9d2cac3be42bdbfec28fd9af8e28"
      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
  end

  test do
    # Smoke test: derive a pubkey from a known passphrase on p256 and
    # compare against the byte-equal py-seccure / C-reference output.
    assert_equal "!,jPO$#,mkJl2(^tiQ]q6h[x~xA${!tGw8acQP_:",
      shell_output("#{bin}/seccure-key -c p256 -p Test1234").strip
  end
end
