# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoSeccure < Formula
  desc "Pure-Go port of SECCURE — byte-compatible with the C reference and py-seccure across all 15 curves."
  homepage "https://github.com/invenity-labs/go-seccure"
  version "0.2.0"
  license "LGPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.0/go-seccure_0.2.0_darwin_amd64.tar.gz"
      sha256 "fb0fcfb1fb6a414964136203c86673032bf8ba5f1bba376492cba1dddd7df23b"

      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.0/go-seccure_0.2.0_darwin_arm64.tar.gz"
      sha256 "df39eaac9014318c218ddf10d76a34f518ce057bb9cacf289e533b7a99790e4f"

      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.0/go-seccure_0.2.0_linux_amd64.tar.gz"
      sha256 "7941a31b1f558afc6d7c6b2e31b313b089926d3c5c7428f56ee18256fa8bbb50"
      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/invenity-labs/go-seccure/releases/download/v0.2.0/go-seccure_0.2.0_linux_arm64.tar.gz"
      sha256 "50b6eefe26e40f8c353b7643a93f323eb1a5fe7804f603da912a4486af6178c0"
      define_method(:install) do
        bin.install Dir["seccure-*"]
      end
    end
  end

  test do
    # Smoke test: derive a pubkey from a known passphrase on p256 and
    # compare against the byte-equal py-seccure / C-reference output.
    assert_equal "!,jPO$#,mkJl2(^tiQ]q6h[x~xA${!tGw8acQP_:",
      shell_output("#{bin}/seccure-key -c p256 -p Test1234").strip
  end
end
